"""
redocking/src/make_haddock_cfg.py
====================================
Stage 5: per-complex HADDOCK3 .cfg, adapted from haddock3's own
`examples/docking-protein-ligand/docking-protein-ligand-full.cfg` template
(module order: topoaa -> rigidbody -> caprieval -> seletop -> flexref ->
ilrmsdmatrix -> clustrmsd -> seletopclusts -> caprieval) -- this is the
reference protocol being adapted, not a from-scratch workflow design.

Two ligand-topology modes, selected with --autotoppar:
  - default: ligand_top_fname/ligand_param_fname point at
    ligand_topology/GA1_cns.top / GA1_cns.param (prep_ligand_topology.py's
    BioExcel/acpype output).
  - --autotoppar: HADDOCK3's [topoaa] autotoppar=true instead -- generates
    ligand topology directly from data/ga1_from_ga3.sdf-derived PDB, no
    acpype dependency. Fast cross-check / fallback if the acpype route
    isn't validated yet (see prep_ligand_topology.py's module docstring).

**Confirmed by hand against a real run (2026-08-25) -- NOT guessable from
the fetched upstream example alone**: `ligand_top_fname`/`ligand_param_fname`
set only under `[topoaa]` are NOT automatically carried through to later
CNS-running modules ([rigidbody], [flexref], ...) for the manual/acpype
route. HADDOCK3's own topoaa source
(`haddock/modules/topology/topoaa/__init__.py`) only writes these into
`self._output_params` (the mechanism that auto-propagates them onto every
downstream module) inside the `autotoppar` branch, for single-model
inputs -- the plain `ligand_top_fname` branch does not. Concretely: a
`rigidbody` run with only `[topoaa]`'s ligand params set gets an EMPTY
`$ligand_param_fname` in its own generated .inp (confirmed by reading the
decompressed `*.inp`/`*.out.gz` from a `debug = true` run), so CNS never
loads the ligand's GAFF nonbonded (Lennard-Jones) parameters and aborts
with `%NBUPDA-ERR: missing nonbonded Lennard-Jones parameters` the moment
the energy term needs them. **Every module in `CNS_LIGAND_MODULES` below
needs its own `ligand_top_fname`/`ligand_param_fname` lines**, not just
`[topoaa]` -- confirmed this is genuinely module-scoped (each of
rigidbody/flexref/emref/mdref/etc. has its own `ligand_param_fname` entry
in its own `defaults.yaml`, defaulting to empty string). Not needed for
`--autotoppar`, since that branch's own propagation already covers it for
this pilot's single-model (non-ensemble) case.

Output: results/haddock_runs/<complex_id>/run.cfg (haddock3's own run
directory is created by haddock3 itself on execution, not here).
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import config
from extract_receptor_pdb import RECEPTOR_DIR
from define_active_passive import RESTRAINTS_DIR

# Every module downstream of [topoaa] that runs its own CNS energy
# evaluation on the complex needs the ligand's custom parameters restated
# -- see module docstring. caprieval/seletop/ilrmsdmatrix/clustrmsd/
# seletopclusts don't run CNS minimization and don't take this parameter.
CFG_TEMPLATE = """\
# Generated by redocking/src/make_haddock_cfg.py -- adapted from haddock3's
# examples/docking-protein-ligand/docking-protein-ligand-full.cfg
run_dir = "{run_dir}"
molecules = ["{receptor_pdb}", "{ligand_pdb}"]

[topoaa]
{topoaa_ligand_block}

[rigidbody]
{ligand_block}
ambig_fname = "{ambig_tbl}"
sampling = 200

[caprieval]
reference_fname = "{receptor_pdb}"

[seletop]
select = 40

[flexref]
{ligand_block}
ambig_fname = "{ambig_tbl}"

[caprieval]

[ilrmsdmatrix]

[clustrmsd]
criterion = "maxclust"
n_clusters = 4

[seletopclusts]
top_models = 4

[caprieval]
"""

LIGAND_PARAM_BLOCK = """\
ligand_top_fname = "{top}"
ligand_param_fname = "{param}"
"""

TOPOAA_AUTOTOPPAR_BLOCK = """\
autotoppar = true
"""


def make_cfg(complex_id: str, receptor_pdb: Path, ligand_pdb: Path, ambig_tbl: Path,
             run_dir: Path, out_cfg: Path, autotoppar: bool) -> Path:
    if autotoppar:
        topoaa_block = TOPOAA_AUTOTOPPAR_BLOCK
        ligand_block = ""  # autotoppar's own single-model propagation covers rigidbody/flexref already
    else:
        if not (config.GA1_CNS_TOP.exists() and config.GA1_CNS_PARAM.exists()):
            raise FileNotFoundError(
                f"{config.GA1_CNS_TOP} / {config.GA1_CNS_PARAM} not found -- run "
                f"prep_ligand_topology.py first, or pass --autotoppar to use HADDOCK3's "
                f"built-in ligand-topology generation instead."
            )
        ligand_block = LIGAND_PARAM_BLOCK.format(top=config.GA1_CNS_TOP, param=config.GA1_CNS_PARAM)
        topoaa_block = ligand_block

    cfg_text = CFG_TEMPLATE.format(
        run_dir=run_dir,
        receptor_pdb=receptor_pdb,
        ligand_pdb=ligand_pdb,
        ambig_tbl=ambig_tbl,
        topoaa_ligand_block=topoaa_block,
        ligand_block=ligand_block,
    )
    out_cfg.parent.mkdir(parents=True, exist_ok=True)
    out_cfg.write_text(cfg_text)
    return out_cfg


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--autotoppar", action="store_true",
                         help="Use HADDOCK3's built-in autotoppar ligand-topology generation "
                              "instead of prep_ligand_topology.py's acpype/BioExcel output.")
    args = parser.parse_args()

    if not config.GA1_FROM_GA3_SDF.exists():
        raise FileNotFoundError(f"{config.GA1_FROM_GA3_SDF} not found -- run build_ga1_from_ga3.py first.")
    # HADDOCK3's molecules= list takes PDB, not SDF -- reuse the same
    # OpenBabel standardization prep_ligand_topology.py already does for
    # acpype's input, so both topology modes consume the exact same ligand
    # geometry/atom set.
    from prep_ligand_topology import standardize_with_openbabel
    ligand_pdb = config.DATA_DIR / "_cache" / "GA1_standardized.pdb"
    ligand_pdb.parent.mkdir(parents=True, exist_ok=True)
    standardize_with_openbabel(config.GA1_FROM_GA3_SDF, ligand_pdb)

    with config.MANIFEST_CSV.open() as f:
        rows = list(csv.DictReader(f))

    for row in rows:
        complex_id = row["complex_id"]
        receptor_pdb = RECEPTOR_DIR / f"{complex_id}_receptor.pdb"
        ambig_tbl = RESTRAINTS_DIR / f"{complex_id}_ambig.tbl"
        run_dir = config.HADDOCK_RUNS_DIR / complex_id
        out_cfg = run_dir / "run.cfg"
        make_cfg(complex_id, receptor_pdb, ligand_pdb, ambig_tbl, run_dir, out_cfg, args.autotoppar)
        print(f"{complex_id}: wrote {out_cfg}")


if __name__ == "__main__":
    main()
